name: Deployment Workflow
on:
  push:
    branches:
      - 'main'
    paths:
      - docs/**

jobs:
  job_one:
    name: build
    runs-on: ubuntu-latest
    env:
      INPUTPATH: docs
      OUTPUTPATH: dist
      SLIDES: false
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: quirinecker/asciidoctor-convert-action@main
        with:
          slides: ${{ env.SLIDES }}
          inputPath: ${{ env.INPUTPATH }}
          outputPath: ${{ env.OUTPUTPATH }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FOLDER: ${{ env.OUTPUTPATH }}
  job_two:
    needs: job_one
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing oracle server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 152.70.179.243
        username: ubuntu
        key: ${{ secrets.MYSECRET }}
        port: 22
        script: |
          cd actions-as-code
          git switch gh-pages
          git pull
