name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: convert
    runs-on: ubuntu-latest
    steps:
    - name: Asciidoctor Convert Action
      uses: quirinecker/asciidoctor-convert-action@1.3
      with:
        slides: true
        inputPath: input
        outputPath: output
  job_two:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing oracle server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 152.70.179.243
        username: ubuntu
        key: ${{ secrets.MYSECRET }}
        port: 22
        script: |
          ls -al
  